spring:
  application:
    name: review-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: orders-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.type.mapping": "bookRatingUpdateEvent:org.example.reviewservice.dto.BookRatingUpdateEvent"
  datasource:
    url: jdbc:mariadb://localhost:3306/library
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka